---
title: "P8105_hw2"
author: "Dianchen Li"
date: "2025-09-30"
output: github_document
---

```{r}
library(tidyverse)
library(janitor)
library(here)
library(readxl)
library(stringr)
```
#Problem 1
## Tidy up pols_month.csv
```{r}
pols = 
  read_csv(here("pols-month.csv")) %>% 
  clean_names() %>% 
  separate(mon, into = c("year", "month", "day"), sep = "-", convert = TRUE) %>% 
  mutate(
    month = tolower(month.name[month]),
    president = if_else(prez_gop == 1, "gop", "dem")
  ) %>% 
  select(year, month, president,
         gov_gop, sen_gop, rep_gop,
         gov_dem, sen_dem, rep_dem) %>% 
  arrange(year, month)

```

##Tidy up snp.csv
```{r}
snp = 
  read_csv(here("snp.csv")) %>% 
  clean_names() %>% 
  separate(date, into = c("month", "day", "year"), sep = "/", convert = TRUE) %>% 
  mutate(
    year = year + 2000,
    year = if_else(year > 2015, year - 100, year),
    month = tolower(month.name[month])
  ) %>% 
  select(year, month, close) %>% 
  arrange(year, month)
```
## Tidy up unemployment.csv
```{r}
unemp = 
  read_csv(here("unemployment.csv")) %>% 
  clean_names() %>% 
  pivot_longer(
    jan:dec, 
    names_to = "month_abbr", values_to = "unemployment"
  ) %>% 
  mutate(
    month = recode(month_abbr,
      "jan" = "january", "feb" = "february", "mar" = "march",
      "apr" = "april",   "may" = "may",       "jun" = "june",
      "jul" = "july",    "aug" = "august",    "sep" = "september",
      "oct" = "october", "nov" = "november",  "dec" = "december"
    )
  ) %>% 
  select(year, month, unemployment) %>% 
  arrange(year, month)

```
##Combine each dataset
```{r}
merged_df <- 
  pols %>% 
  left_join(snp,   by = c("year", "month")) %>% 
  left_join(unemp, by = c("year", "month")) %>% 
  arrange(year, month)

```

#Problem 2
```{r}
tw_path = here( "202409 Trash Wheel Collection Data.xlsx")
```

##Specify which column we want to keep
```{r}
wanted_cols = c(
  "dumpster", "month", "year", "date",
  "weight_tons", "volume_cubic_yards",
  "plastic_bottles", "polystyrene",
  "cigarette_butts", "glass_bottles",
  "grocery_bags", "chip_bags",
  "sports_balls", "homes_powered"
)

read_clean_trash = function(sheet_name, wheel_label) {
  raw = read_excel(
    path  = tw_path,
    sheet = sheet_name,
    skip  = 1
  ) %>%
    clean_names()

  keep = intersect(wanted_cols, names(raw))

  raw %>%
    select(all_of(keep)) %>%
    filter(!is.na(dumpster)) %>%
    mutate(
      month = str_to_title(as.character(month)),
      date  = as.Date(date),
      year  = as.integer(year),
      sports_balls = as.integer(round(sports_balls)),
      wheel = wheel_label
    )
}
```











